version: "3.8"
services:
  app:
    container_name: "php"
    build:
      context: ./infra/php
      args:
        - http_proxy=$HTTP_PROXY
        - https_proxy=$HTTPS_PROXY
        - no_proxy=$NO_PROXY
    environment:
      - http_proxy=$HTTP_PROXY
      - https_proxy=$HTTPS_PROXY
      - no_proxy=$NO_PROXY
    volumes:
      - ./backend:/var/www/html
    ports:
      - "10080:80"

  db:
    container_name: "postgres"
    build:
      context: ./infra/postgres
    volumes:
      - ./infra/postgres/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel_local

volumes:
  db-store: